version: "3.8"
services:
  postgres:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=corybuecker
    ports:
      - 5432:5432
  redis:
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379
