# fly.toml file generated for simple-budget-rails on 2023-04-10T08:40:34-05:00

app = "simple-budget-rails"
primary_region = "dfw"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 50
    soft_limit = 25
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
